---
- hosts: all
  become: true
  tasks:
    - name: Set SELinux to permissive
      ansible.posix.selinux:
        policy: targeted

    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started

    - name: Set time to New York
      community.general.timezone:
        name: America/New_York
