---
- name: Setup RHEL configuration files
  hosts: all
  tasks:
  - name: Set SELINUX to permissive
    ansible.posix.selinux:
      policy: targeted
      state: permissive
  - name: Ensure that firewalld is enabled and running
    ansible.builtin.systemd:
      name: firewalld
      state: started
      enabled: true
  - name: Make sure that cockpit is enabled and running
    ansible.builtin.systemd:
      name: cockpit
      state: started
      enabled: true
  - name: Sync clock to New York time
    ansible.builtin.command: ntpdate -u 1.rhel.pool.ntp.org