---
- name: Test for lightspeed
  hosts: all

  tasks:
    - name: Update all RHEL packages
      when: ansible_distribution == 'RedHat'
      ansible.builtin.package:
        name: "*"
        state: latest
    - name: Run the "sync" command
      ansible.builtin.command: /usr/local/bin/sync
      when: ansible_distribution == 'RedHat'
    - name: Message users using the "wall" command that the system will reboot in 1 minute
      ansible.builtin.command: /usr/bin/wall -n "System rebooting in 60 seconds"
    - name: Sleep for 60 seconds
      ansible.builtin.wait_for:
        timeout: 60
      when: ansible_distribution == 'RedHat'
    - name: reboot the system in 60 seconds
      ansible.builtin.command: /sbin/reboot
      when: ansible_distribution == 'RedHat'
