---
- name: Test for lightspeed
  hosts: all

  tasks:
    - name: Update all RHEL packages
      when: ansible_distribution == 'RedHat'
      ansible.builtin.package:
        name: "*"

    - name: Run the "sync" command
      ansible.builtin.command: /usr/local/bin/sync

    - name: Message users using the "wall" command that the system will reboot in 1 minute

    - name: Sleep for 60 seconds
      ansible.builtin.wait_for:
        timeout: 60

    - name: reboot the system in 60 seconds
      ansible.builtin.command: /sbin/reboot
      when: ansible_distribution == 'RedHat'
