---
- hosts: all
  become: true
  tasks:
    - name: Check for updates
      yum:
        name: "*"
        state: latest
        update_cache: true
    - name: Print list of updates
      debug:
        var: yum_updates
