---
- hosts: all
  become: true
  tasks:
    - name: Check for updates
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Print list of updates
      ansible.builtin.debug:
        var: yum_updates
